# Generated by Django 4.0.5 on 2022-06-23 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_alter_tournament_creator_alter_tournament_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='names',
            new_name='name',
        ),
    ]
